# Generated by Django 5.1.1 on 2024-09-15 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_last_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='online_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
