# Generated by Django 5.1.1 on 2024-09-16 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_online_time_onlineuseractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuseractivity',
            name='online_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='onlineuseractivity',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
