# Generated by Django 5.1.1 on 2024-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_onlineuseractivity_online_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineuseractivity',
            name='online_time',
        ),
        migrations.AlterField(
            model_name='onlineuseractivity',
            name='last_activity',
            field=models.DateTimeField(),
        ),
    ]
